mc.version.title = 1.21-1.21.1
mc.version.supported = 1.21, 1.21.1

fabric.loom = remap

mixins.extra.client = \
  MixinClientCommonNetworkHandler,\
  gui.screen.MixinAbstractFurnaceScreen,\
  gui.screen.MixinCraftingTableScreen,\
  gui.screen.MixinInventoryScreen

preprocessor.mc_version_number = 12101
